// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdzunfovvejxtrnecegg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkenVuZm92dmVqeHRybmVjZWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MTM4NjcsImV4cCI6MjA2ODI4OTg2N30.kK0qvQjAuHp6U0wW5kzngwNsqRXI_DhGg61iVNaDZR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});